### ISSUE TITLE
[Docs]: Add icons for important links on top bar

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The footer in the new Docusaurus site does not have relevant information. It was added there to primarily contain the links for discord, twitter, youtube, github etc.  On Docusaurus, we had to do this using swizzle.(https://github.com/facebook/docusaurus/issues/2634) and it would have delayed the project trying to figure out this part. 

In the next iteration, we can add these icons on the topbar and remove the footer.

### Describe the improvement

na

### Why do you think this change is needed?

na
```[tasklist]
### Tasks
- [ ] Add important icons on top bar
- [ ] https://github.com/appsmithorg/appsmith-docs/pull/1693
```

**Comment by jnikhila** [comment]
As discussed, FYI - @tejasahluwalia
